# Generated by Django 5.2.13 on 2026-06-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_form',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
