# Generated by Django 4.2.30 on 2026-04-09 03:45

from django.db import migrations, models
import django.db.models.deletion
import landnest_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnPlans',
            fields=[
                ('addOn_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('Buyer', 'Buyer'), ('Tenant', 'Tenant'), ('Individual Owner/Builder', 'Individual Owner/Builder'), ('Landlord', 'Landlord'), ('Agent', 'Agent'), ('Bank Auction', 'Bank Auction')], max_length=100)),
                ('actual_price', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('charges', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('buyer_no_unlimited', models.BooleanField(default=False)),
                ('buyer_no', models.BigIntegerField(blank=True, null=True)),
                ('no_of_properties_unlimited', models.BooleanField(default=False)),
                ('no_of_liked_data_unlimited', models.BooleanField(default=False)),
                ('matching_enquiry_unlimited', models.BooleanField(default=False)),
                ('no_of_properties', models.BigIntegerField(blank=True, null=True)),
                ('no_of_liked_data', models.BigIntegerField(blank=True, null=True)),
                ('matching_enquiry', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='construction_cat',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('Elevation', 'Elevation'), ('2D-Interiors', '2D-Interiors'), ('3D-Interiors', '3D-Interiors')], max_length=100)),
                ('sub_cat', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='construction_content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='media/construction_content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='material_cat',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='material_content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='media/material_content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('max_discount_amount', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('no_of_times', models.IntegerField(blank=True, default=1, null=True)),
                ('valid_life_time', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='offerurls',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('offername', models.CharField(blank=True, max_length=255, null=True)),
                ('offerurl', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('package_cost', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('tile_general', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('tile_stair', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('tile_balcony', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('title_bathroom', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('tile_parking', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('tile_kitchen_countertop', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('tile_kitchen_backsplash', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('window_ms_grill', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('window_standered', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('doors_main', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('doors_pooja', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('doors_internal', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('fabrication_stair_rail', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('fabrication_gate', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('sanitary_overheadtank', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('sanitary_commode', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('sanitary_wallmixer', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('sanitary_sewage_chamber', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='referral_reward',
            fields=[
                ('rew_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_users', models.BigIntegerField(blank=True, null=True)),
                ('credit_points', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subAdminplans',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('razor_plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_name', models.CharField(blank=True, choices=[('Free', 'Free'), ('1 Months', '1 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('Lifetime', 'Lifetime')], max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('Buyer', 'Buyer'), ('Tenant', 'Tenant'), ('Individual Owner/Builder', 'Individual Owner/Builder'), ('Landlord', 'Landlord'), ('Builder', 'Builder'), ('Agent', 'Agent'), ('Bank Auction', 'Bank Auction')], max_length=100, null=True)),
                ('actual_price', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('charges', landnest_admin.models.CleanFloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('trial_days', models.BigIntegerField(blank=True, null=True)),
                ('buyer_no_unlimited', models.BooleanField(default=False)),
                ('buyer_no', models.BigIntegerField(blank=True, null=True)),
                ('no_of_properties_unlimited', models.BooleanField(default=False)),
                ('no_of_liked_data_unlimited', models.BooleanField(default=False)),
                ('matching_enquiry_unlimited', models.BooleanField(default=False)),
                ('no_of_properties', models.BigIntegerField(blank=True, null=True)),
                ('no_of_liked_data', models.BigIntegerField(blank=True, null=True)),
                ('matching_enquiry', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOfferClaim',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claimed_status', models.BooleanField(default=False)),
                ('no_of_times', models.IntegerField(blank=True, default=1, null=True)),
                ('no_of_claimed', models.IntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_claims', to='landnest_admin.offers')),
            ],
        ),
    ]
