# Generated by Django 5.2.13 on 2026-05-28 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankauctionproperty',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_prop', to='users.user'),
        ),
        migrations.AddField(
            model_name='bankauctionpropertydocs',
            name='bankpro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_pro_doc', to='property.bankauctionproperty'),
        ),
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_properties', to='users.user'),
        ),
        migrations.AddField(
            model_name='property_cat',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='property',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property_cat'),
        ),
        migrations.AddField(
            model_name='property_images',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prop_req', to='users.user'),
        ),
        migrations.AddField(
            model_name='propertyrequestlocations',
            name='req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_loc', to='property.propertyrequest'),
        ),
        migrations.AddField(
            model_name='responsepropertyrequest',
            name='req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_req', to='property.propertyrequest'),
        ),
        migrations.AddField(
            model_name='responsepropertyrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prop_res', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['lat', 'long'], name='property_pr_lat_9540d4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'Admin_status'], name='property_pr_type_2129b3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'property_type'], name='property_pr_type_50a54e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'posted_by'], name='property_pr_type_9fb0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'posted_by'], name='property_pr_propert_c62208_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'property_type', 'Admin_status'], name='property_pr_type_3e39e5_idx'),
        ),
    ]
