# Generated by Django 4.2.30 on 2026-04-09 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsepropertyrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prop_res', to='users.user'),
        ),
        migrations.AddField(
            model_name='propertyrequestlocations',
            name='req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_loc', to='property.propertyrequest'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prop_req', to='users.user'),
        ),
        migrations.AddField(
            model_name='property_images',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property'),
        ),
        migrations.AddField(
            model_name='property_cat',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='property',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property_cat'),
        ),
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_properties', to='users.user'),
        ),
        migrations.AddField(
            model_name='bankauctionpropertydocs',
            name='bankpro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_pro_doc', to='property.bankauctionproperty'),
        ),
        migrations.AddField(
            model_name='bankauctionproperty',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_prop', to='users.user'),
        ),
    ]
