# Generated by Django 4.2.30 on 2026-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['lat', 'long'], name='property_pr_lat_9540d4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'Admin_status'], name='property_pr_type_2129b3_idx'),
        ),
    ]
