# Generated by Django 5.2.13 on 2026-08-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_bankauctionproperty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankauctionproperty',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankauctionproperty',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
