# Generated by Django 4.2.9 on 2026-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_property_pr_lat_9540d4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='long',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True),
        ),
    ]
