# Generated by Django 4.2.9 on 2026-05-06 11:24

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_lat_alter_property_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=property.models.CleanFloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='property_cat',
            name='category_type',
            field=models.CharField(choices=[('sell', 'sell'), ('rent/lease', 'Rent/Lease')], max_length=50),
        ),
    ]
