# Generated by Django 5.2.13 on 2026-08-31 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_bankauctionproperty_admin_status_and_more'),
        ('users', '0002_enquiry_form_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdProperty',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('admin_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('Admin_status', models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True)),
                ('property_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('property_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True)),
                ('long', models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('min_budget', models.FloatField(blank=True, null=True)),
                ('max_budget', models.FloatField(blank=True, null=True)),
                ('min_acres', models.FloatField(blank=True, null=True)),
                ('max_acres', models.FloatField(blank=True, null=True)),
                ('ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('roadwidth', models.FloatField(blank=True, null=True)),
                ('site_area', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('buildup_area', models.FloatField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, db_index=True, null=True)),
                ('nearby', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_floors', models.IntegerField(blank=True, db_index=True, null=True)),
                ('rooms_count', models.IntegerField(blank=True, null=True)),
                ('duplex_bedrooms', models.IntegerField(blank=True, null=True)),
                ('bedrooms_count', models.IntegerField(blank=True, null=True)),
                ('bathrooms_count', models.IntegerField(blank=True, null=True)),
                ('shop_count', models.IntegerField(blank=True, null=True)),
                ('house_count', models.IntegerField(blank=True, null=True)),
                ('facing', models.CharField(blank=True, max_length=50, null=True)),
                ('balcony', models.CharField(blank=True, max_length=200, null=True)),
                ('power_backup', models.CharField(blank=True, max_length=200, null=True)),
                ('gated_security', models.CharField(blank=True, max_length=200, null=True)),
                ('borewell', models.CharField(blank=True, max_length=200, null=True)),
                ('parking', models.CharField(blank=True, max_length=200, null=True)),
                ('lift', models.CharField(blank=True, max_length=200, null=True)),
                ('advance_payment', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('adstart_date', models.DateTimeField(blank=True, null=True)),
                ('adend_date', models.DateTimeField(blank=True, null=True)),
                ('boost_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_properties', to='property.property_cat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_adproperties', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdProperty_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/AdProperty_hero_images/')),
                ('order', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='property.adproperty')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdPropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='property.adproperty')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdPropertyBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='media/AdProperty_brochures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochures', to='property.adproperty')),
            ],
        ),
        migrations.CreateModel(
            name='AdPropertyBuilderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('ongoing_projects', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_details', to='property.adproperty')),
            ],
        ),
        migrations.CreateModel(
            name='AdPropertyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk_type', models.CharField(choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('4+BHK', '4+ BHK')], max_length=20)),
                ('carpet_area', models.FloatField(blank=True, null=True)),
                ('built_up_area', models.FloatField(blank=True, null=True)),
                ('super_built_up_area', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('facing', models.CharField(blank=True, max_length=50, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('balcony', models.PositiveIntegerField(blank=True, null=True)),
                ('parking', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='property.adproperty')),
            ],
            options={
                'ordering': ['bhk_type'],
            },
        ),
        migrations.CreateModel(
            name='AdPropertyFloorPlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('2D', '2D'), ('3D', '3D')], max_length=10)),
                ('image', models.ImageField(upload_to='media/AdProperty_floor_plans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_images', to='property.adpropertyconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='AdPropertyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_highlights', to='property.adproperty')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdPropertyLocationAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('distance', models.CharField(help_text='Example: 2.5 km', max_length=100)),
                ('travel_time', models.CharField(help_text='Example: 10 min', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_advantages', to='property.adproperty')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdPropertySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.TextField(max_length=1000)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='property.adproperty')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='adproperty',
            index=models.Index(fields=['lat', 'long'], name='property_ad_lat_bc309e_idx'),
        ),
        migrations.AddIndex(
            model_name='adproperty',
            index=models.Index(fields=['type', 'Admin_status'], name='property_ad_type_346ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='adproperty',
            index=models.Index(fields=['type', 'property_type'], name='property_ad_type_7eedbd_idx'),
        ),
        migrations.AddIndex(
            model_name='adproperty',
            index=models.Index(fields=['type', 'posted_by'], name='property_ad_type_c301bf_idx'),
        ),
        migrations.AddIndex(
            model_name='adproperty',
            index=models.Index(fields=['property_type', 'posted_by'], name='property_ad_propert_fe4eed_idx'),
        ),
        migrations.AddIndex(
            model_name='adproperty',
            index=models.Index(fields=['type', 'property_type', 'Admin_status'], name='property_ad_type_e4b81c_idx'),
        ),
        migrations.AddIndex(
            model_name='adproperty',
            index=models.Index(fields=['city', 'property_type'], name='property_ad_city_a963a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='adproperty_images',
            constraint=models.UniqueConstraint(fields=('property', 'order'), name='unique_property_hero_image_order'),
        ),
        migrations.AddConstraint(
            model_name='adpropertyconfiguration',
            constraint=models.UniqueConstraint(fields=('property', 'bhk_type'), name='unique_property_bhk_configuration'),
        ),
        migrations.AddConstraint(
            model_name='adpropertyfloorplanimage',
            constraint=models.UniqueConstraint(fields=('configuration', 'plan_type'), name='unique_configuration_plan_type'),
        ),
        migrations.AddConstraint(
            model_name='adpropertylocationadvantage',
            constraint=models.UniqueConstraint(fields=('property', 'order'), name='unique_property_location_order'),
        ),
    ]
