# Generated by Django 4.2.9 on 2026-05-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_price_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bankauctionproperty',
            index=models.Index(fields=['user_id'], name='property_ba_user_id_e0d8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='bankauctionproperty',
            index=models.Index(fields=['property_type'], name='property_ba_propert_21f0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='bankauctionproperty',
            index=models.Index(fields=['bank_name'], name='property_ba_bank_na_6569b9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankauctionproperty',
            index=models.Index(fields=['city_town'], name='property_ba_city_to_164553_idx'),
        ),
        migrations.AddIndex(
            model_name='bankauctionproperty',
            index=models.Index(fields=['status'], name='property_ba_status_5681fb_idx'),
        ),
        migrations.AddIndex(
            model_name='bankauctionproperty',
            index=models.Index(fields=['created_at'], name='property_ba_created_b724e3_idx'),
        ),
        migrations.AddIndex(
            model_name='bankauctionproperty',
            index=models.Index(fields=['user_id', 'property_type'], name='property_ba_user_id_938876_idx'),
        ),
        migrations.AddIndex(
            model_name='bankauctionproperty',
            index=models.Index(fields=['property_type', 'status'], name='property_ba_propert_018d8e_idx'),
        ),
    ]
