# Generated by Django 4.2.9 on 2026-05-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_bankauctionproperty_property_ba_user_id_e0d8bb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankauctionproperty',
            name='property_ba_user_id_e0d8bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankauctionproperty',
            name='property_ba_propert_21f0b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankauctionproperty',
            name='property_ba_bank_na_6569b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankauctionproperty',
            name='property_ba_city_to_164553_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankauctionproperty',
            name='property_ba_status_5681fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankauctionproperty',
            name='property_ba_created_b724e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankauctionproperty',
            name='property_ba_user_id_938876_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankauctionproperty',
            name='property_ba_propert_018d8e_idx',
        ),
    ]
