# Generated by Django 5.2.13 on 2026-05-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_bankauctionproperty_property_ba_user_id_e0d8bb_idx_and_more'),
        ('users', '0004_alter_user_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Admin_status',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='_1bhk_count',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='_2bhk_count',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='_3bhk_count',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='_4bhk_count',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_flores',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='posted_by',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'property_type'], name='property_pr_type_50a54e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'posted_by'], name='property_pr_type_9fb0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'posted_by'], name='property_pr_propert_c62208_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'property_type', 'Admin_status'], name='property_pr_type_3e39e5_idx'),
        ),
    ]
